import { Metadata } from "next";
import Navbar from "../../components/AppLayout/Navbar";
import Sidebar from "../../ui/Sidebar";
import RecoilContextProvider from "@/app/RecoilState/RecoilContextProvider";

export const metadata: Metadata = {
  title: "Dashboard | Zapier",
  description: "Generated by create next app",
  icons: "https://cdn.zapier.com/zapier/images/favicon.ico",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <RecoilContextProvider>
      {" "}
      {/* Single provider for the entire layout */}
      <div className="flex flex-col h-full w-full">
        <Navbar />
        <div className="flex h-full w-full">
          <Sidebar />
          <div className="flex justify-center w-full h-full">
            <div className="w-11/12 max-w-7xl mt-6 mr-1 flex flex-col">
              {children}
            </div>
          </div>
        </div>
      </div>
    </RecoilContextProvider>
  );
}
