import RecoilContextProvider from "@/app/RecoilState/RecoilContextProvider";
import { Metadata } from "next";
import LeftBar from "./LeftBar";
import TopBar from "./TopBar";

export const metadata: Metadata = {
  title: "Create | Zapier",
  description: "Generated by create next app",
  icons: "https://cdn.zapier.com/zapier/images/favicon.ico",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen h-screen">
      <RecoilContextProvider>
        <div className="flex flex-col min-h-screen h-screen">
          <TopBar />
          <div className="flex h-full">
            <LeftBar />
            <div className="w-full rounded-md min-h-full">{children}</div>
          </div>
        </div>
      </RecoilContextProvider>
    </div>
  );
}
