import { Metadata } from "next";
import Navbar from "../components/AppLayout/Navbar";

export const metadata: Metadata = {
  title: "Dashboard | Zapier",
  description: "Generated by create next app",
  icons: "https://cdn.zapier.com/zapier/images/favicon.ico",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
