// import { Field } from "@repo/types";

// const sampleFields: Field[] = [
//   {
//     name: "to",
//     fieldInputType: "text",
//     fieldLabel: "To",
//     fieldPlaceholder: "",
//     fieldValue: "jj",
//     required: true,
//     fieldNumber: 1,
//   },
//   {
//     name: "subject",
//     fieldInputType: "text",
//     fieldLabel: "Subject",
//     fieldPlaceholder: "",
//     fieldValue: "j",
//     required: true,
//     fieldNumber: 2,
//   },
//   {
//     name: "body",
//     fieldInputType: "textarea",
//     fieldLabel: "Body",
//     fieldPlaceholder: "",
//     fieldValue: "jj",
//     required: true,
//     fieldNumber: 3,
//   },
//   {
//     name: "attachment",
//     fieldInputType: "file",
//     fieldLabel: "Attachment",
//     fieldPlaceholder: "",
//     fieldValue: null,
//     required: false,
//     fieldNumber: 4,
//   },
//   {
//     name: "fromName",
//     fieldInputType: "text",
//     fieldLabel: "From Name",
//     fieldPlaceholder: "",
//     fieldValue: null,
//     required: false,
//     fieldNumber: 5,
//   },
//   {
//     name: "replyTo",
//     fieldInputType: "email",
//     fieldLabel: "Reply To",
//     fieldPlaceholder: "",
//     fieldValue: null,
//     required: false,
//     fieldNumber: 6,
//   },
//   {
//     name: "cc",
//     fieldInputType: "text",
//     fieldLabel: "Cc",
//     fieldPlaceholder: "",
//     fieldValue: null,
//     required: false,
//     fieldNumber: 7,
//   },
// ];
