import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilContextProvider from "./RecoilState/RecoilContextProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: "#FFFDF9" }}
        className={`${inter.variable} font-sans antialiased`}
      >
        <RecoilContextProvider>{children}</RecoilContextProvider>
      </body>
    </html>
  );
}
